import { createSlice } from "@reduxjs/toolkit";

export const mvpListSlice = createSlice({
  name: "mvpList",
  initialState: {
    mvpList: [
      {
        username: "Wokkta",
        commitsTotal: 93,
        issuesTotal: 153,
        pullRequestTotal: 122,
        mostUsedLanguage: "js",
      },
      {
        username: "Tolik",
        commitsTotal: 19,
        issuesTotal: 161,
        pullRequestTotal: 143,
        mostUsedLanguage: "python",
      },
      {
        username: "Wort",
        commitsTotal: 1113,
        issuesTotal: 13,
        pullRequestTotal: 12,
        mostUsedLanguage: "java",
      },
      {
        username: "Wokkta",
        commitsTotal: 93,
        issuesTotal: 153,
        pullRequestTotal: 122,
        mostUsedLanguage: "js",
      },
      {
        username: "Tolik",
        commitsTotal: 19,
        issuesTotal: 161,
        pullRequestTotal: 143,
        mostUsedLanguage: "python",
      },
      {
        username: "Wort",
        commitsTotal: 1113,
        issuesTotal: 13,
        pullRequestTotal: 12,
        mostUsedLanguage: "java",
      },
      {
        username: "Wokkta",
        commitsTotal: 93,
        issuesTotal: 153,
        pullRequestTotal: 122,
        mostUsedLanguage: "js",
      },
      {
        username: "Tolik",
        commitsTotal: 19,
        issuesTotal: 161,
        pullRequestTotal: 143,
        mostUsedLanguage: "python",
      },
      {
        username: "Wort",
        commitsTotal: 1113,
        issuesTotal: 13,
        pullRequestTotal: 12,
        mostUsedLanguage: "java",
      },
      {
        username: "Wokkta",
        commitsTotal: 93,
        issuesTotal: 153,
        pullRequestTotal: 122,
        mostUsedLanguage: "js",
      },
      {
        username: "Tolik",
        commitsTotal: 19,
        issuesTotal: 161,
        pullRequestTotal: 143,
        mostUsedLanguage: "python",
      },
      {
        username: "Wort",
        commitsTotal: 1113,
        issuesTotal: 13,
        pullRequestTotal: 12,
        mostUsedLanguage: "java",
      },
      {
        username: "Wokkta",
        commitsTotal: 93,
        issuesTotal: 153,
        pullRequestTotal: 122,
        mostUsedLanguage: "js",
      },
      {
        username: "Tolik",
        commitsTotal: 19,
        issuesTotal: 161,
        pullRequestTotal: 143,
        mostUsedLanguage: "python",
      },
      {
        username: "Wort",
        commitsTotal: 1113,
        issuesTotal: 13,
        pullRequestTotal: 12,
        mostUsedLanguage: "java",
      },
      {
        username: "Wokkta",
        commitsTotal: 93,
        issuesTotal: 153,
        pullRequestTotal: 122,
        mostUsedLanguage: "js",
      },
      {
        username: "Tolik",
        commitsTotal: 19,
        issuesTotal: 161,
        pullRequestTotal: 143,
        mostUsedLanguage: "python",
      },
      {
        username: "Wort",
        commitsTotal: 1113,
        issuesTotal: 13,
        pullRequestTotal: 12,
        mostUsedLanguage: "java",
      },
      {
        username: "Wokkta",
        commitsTotal: 93,
        issuesTotal: 153,
        pullRequestTotal: 122,
        mostUsedLanguage: "js",
      },
      {
        username: "Tolik",
        commitsTotal: 19,
        issuesTotal: 161,
        pullRequestTotal: 143,
        mostUsedLanguage: "python",
      },
      {
        username: "Wort",
        commitsTotal: 1113,
        issuesTotal: 13,
        pullRequestTotal: 12,
        mostUsedLanguage: "java",
      },
      {
        username: "Wokkta",
        commitsTotal: 93,
        issuesTotal: 153,
        pullRequestTotal: 122,
        mostUsedLanguage: "js",
      },
      {
        username: "Tolik",
        commitsTotal: 19,
        issuesTotal: 161,
        pullRequestTotal: 143,
        mostUsedLanguage: "python",
      },
      {
        username: "Wort",
        commitsTotal: 1113,
        issuesTotal: 13,
        pullRequestTotal: 12,
        mostUsedLanguage: "java",
      },
      {
        username: "Wokkta",
        commitsTotal: 93,
        issuesTotal: 153,
        pullRequestTotal: 122,
        mostUsedLanguage: "js",
      },
      {
        username: "Tolik",
        commitsTotal: 19,
        issuesTotal: 161,
        pullRequestTotal: 143,
        mostUsedLanguage: "python",
      },
      {
        username: "Wort",
        commitsTotal: 1113,
        issuesTotal: 13,
        pullRequestTotal: 12,
        mostUsedLanguage: "java",
      },
      {
        username: "Wokkta",
        commitsTotal: 93,
        issuesTotal: 153,
        pullRequestTotal: 122,
        mostUsedLanguage: "js",
      },
      {
        username: "Tolik",
        commitsTotal: 19,
        issuesTotal: 161,
        pullRequestTotal: 143,
        mostUsedLanguage: "python",
      },
      {
        username: "Wort",
        commitsTotal: 1113,
        issuesTotal: 13,
        pullRequestTotal: 12,
        mostUsedLanguage: "java",
      },
      {
        username: "Wokkta",
        commitsTotal: 93,
        issuesTotal: 153,
        pullRequestTotal: 122,
        mostUsedLanguage: "js",
      },
      {
        username: "Tolik",
        commitsTotal: 19,
        issuesTotal: 161,
        pullRequestTotal: 143,
        mostUsedLanguage: "python",
      },
      {
        username: "Wort",
        commitsTotal: 1113,
        issuesTotal: 13,
        pullRequestTotal: 12,
        mostUsedLanguage: "java",
      },
      {
        username: "Wokkta",
        commitsTotal: 93,
        issuesTotal: 153,
        pullRequestTotal: 122,
        mostUsedLanguage: "js",
      },
      {
        username: "Tolik",
        commitsTotal: 19,
        issuesTotal: 161,
        pullRequestTotal: 143,
        mostUsedLanguage: "python",
      },
      {
        username: "Wort",
        commitsTotal: 1113,
        issuesTotal: 13,
        pullRequestTotal: 12,
        mostUsedLanguage: "java",
      },
      {
        username: "Wokkta",
        commitsTotal: 93,
        issuesTotal: 153,
        pullRequestTotal: 122,
        mostUsedLanguage: "js",
      },
      {
        username: "Tolik",
        commitsTotal: 19,
        issuesTotal: 161,
        pullRequestTotal: 143,
        mostUsedLanguage: "python",
      },
      {
        username: "Wort",
        commitsTotal: 1113,
        issuesTotal: 13,
        pullRequestTotal: 12,
        mostUsedLanguage: "java",
      },
      {
        username: "Wokkta",
        commitsTotal: 93,
        issuesTotal: 153,
        pullRequestTotal: 122,
        mostUsedLanguage: "js",
      },
      {
        username: "Tolik",
        commitsTotal: 19,
        issuesTotal: 161,
        pullRequestTotal: 143,
        mostUsedLanguage: "python",
      },
      {
        username: "Wort",
        commitsTotal: 1113,
        issuesTotal: 13,
        pullRequestTotal: 12,
        mostUsedLanguage: "java",
      },
      {
        username: "Wokkta",
        commitsTotal: 93,
        issuesTotal: 153,
        pullRequestTotal: 122,
        mostUsedLanguage: "js",
      },
      {
        username: "Tolik",
        commitsTotal: 19,
        issuesTotal: 161,
        pullRequestTotal: 143,
        mostUsedLanguage: "python",
      },
      {
        username: "Wort",
        commitsTotal: 1113,
        issuesTotal: 13,
        pullRequestTotal: 12,
        mostUsedLanguage: "java",
      },
      {
        username: "Wokkta",
        commitsTotal: 93,
        issuesTotal: 153,
        pullRequestTotal: 122,
        mostUsedLanguage: "js",
      },
      {
        username: "Tolik",
        commitsTotal: 19,
        issuesTotal: 161,
        pullRequestTotal: 143,
        mostUsedLanguage: "python",
      },
      {
        username: "Wort",
        commitsTotal: 1113,
        issuesTotal: 13,
        pullRequestTotal: 12,
        mostUsedLanguage: "java",
      },
      {
        username: "Wokkta",
        commitsTotal: 93,
        issuesTotal: 153,
        pullRequestTotal: 122,
        mostUsedLanguage: "js",
      },
      {
        username: "Tolik",
        commitsTotal: 19,
        issuesTotal: 161,
        pullRequestTotal: 143,
        mostUsedLanguage: "python",
      },
      {
        username: "Wort",
        commitsTotal: 1113,
        issuesTotal: 13,
        pullRequestTotal: 12,
        mostUsedLanguage: "java",
      },
      {
        username: "Wokkta",
        commitsTotal: 93,
        issuesTotal: 153,
        pullRequestTotal: 122,
        mostUsedLanguage: "js",
      },
      {
        username: "Tolik",
        commitsTotal: 19,
        issuesTotal: 161,
        pullRequestTotal: 143,
        mostUsedLanguage: "python",
      },
      {
        username: "Wort",
        commitsTotal: 1113,
        issuesTotal: 13,
        pullRequestTotal: 12,
        mostUsedLanguage: "java",
      },
      {
        username: "Wokkta",
        commitsTotal: 93,
        issuesTotal: 153,
        pullRequestTotal: 122,
        mostUsedLanguage: "js",
      },
      {
        username: "Tolik",
        commitsTotal: 19,
        issuesTotal: 161,
        pullRequestTotal: 143,
        mostUsedLanguage: "python",
      },
      {
        username: "Wort",
        commitsTotal: 1113,
        issuesTotal: 13,
        pullRequestTotal: 12,
        mostUsedLanguage: "java",
      },
      {
        username: "Wokkta",
        commitsTotal: 93,
        issuesTotal: 153,
        pullRequestTotal: 122,
        mostUsedLanguage: "js",
      },
      {
        username: "Tolik",
        commitsTotal: 19,
        issuesTotal: 161,
        pullRequestTotal: 143,
        mostUsedLanguage: "python",
      },
      {
        username: "Wort",
        commitsTotal: 1113,
        issuesTotal: 13,
        pullRequestTotal: 12,
        mostUsedLanguage: "java",
      },
      {
        username: "Wokkta",
        commitsTotal: 93,
        issuesTotal: 153,
        pullRequestTotal: 122,
        mostUsedLanguage: "js",
      },
      {
        username: "Tolik",
        commitsTotal: 19,
        issuesTotal: 161,
        pullRequestTotal: 143,
        mostUsedLanguage: "python",
      },
      {
        username: "Wort",
        commitsTotal: 1113,
        issuesTotal: 13,
        pullRequestTotal: 12,
        mostUsedLanguage: "java",
      },
      {
        username: "Wokkta",
        commitsTotal: 93,
        issuesTotal: 153,
        pullRequestTotal: 122,
        mostUsedLanguage: "js",
      },
      {
        username: "Tolik",
        commitsTotal: 19,
        issuesTotal: 161,
        pullRequestTotal: 143,
        mostUsedLanguage: "python",
      },
      {
        username: "Wort",
        commitsTotal: 1113,
        issuesTotal: 13,
        pullRequestTotal: 12,
        mostUsedLanguage: "java",
      },
      {
        username: "Wokkta",
        commitsTotal: 93,
        issuesTotal: 153,
        pullRequestTotal: 122,
        mostUsedLanguage: "js",
      },
      {
        username: "Tolik",
        commitsTotal: 19,
        issuesTotal: 161,
        pullRequestTotal: 143,
        mostUsedLanguage: "python",
      },
      {
        username: "Wort",
        commitsTotal: 1113,
        issuesTotal: 13,
        pullRequestTotal: 12,
        mostUsedLanguage: "java",
      },
      {
        username: "Wokkta",
        commitsTotal: 93,
        issuesTotal: 153,
        pullRequestTotal: 122,
        mostUsedLanguage: "js",
      },
      {
        username: "Tolik",
        commitsTotal: 19,
        issuesTotal: 161,
        pullRequestTotal: 143,
        mostUsedLanguage: "python",
      },
      {
        username: "Wort",
        commitsTotal: 1113,
        issuesTotal: 13,
        pullRequestTotal: 12,
        mostUsedLanguage: "java",
      },
    ],
  },
  reducers: {
    setMvpList(state, action) {
      state.mvpList = action.payload;
    },
  },
});

// Action creators are generated for each case reducer function
export const { setMvpList } = mvpListSlice.actions;

export default mvpListSlice.reducer;
