import { createSlice } from "@reduxjs/toolkit";

export const mvpListSlice = createSlice({
  name: "mvpList",
  initialState: {
    mvpList: [
      {
        username: "Wokkta",
        commitsTotal: 93,
        issuesTotal: 153,
        pullRequestTotal: 122,
        mostUsedLanguage: "js",
        description: "string",
        displayName: "safas",
        personalWebsite: "string",
        followersCount: 0,
        followingCount: 0,
        location: "string",
        company: "string",
        email: "string",
        languages: {
          additionalProp1: 0,
          additionalProp2: 0,
          additionalProp3: 0,
        },
        activityIndex: 0,
        topLanguage: "string",
        starsCount: 0,
        commitsCount: 0,
        reposCount: 0,
        stackOverflowUrl: "string",
        pullRequestsCount: 0,
        issuesCount: 0,
      },
      {
        username: "Tolik",
        commitsTotal: 19,
        issuesTotal: 161,
        pullRequestTotal: 143,
        mostUsedLanguage: "python",
        description: "string",
        displayName: "string",
        personalWebsite: "string",
        followersCount: 0,
        followingCount: 0,
        location: "string",
        company: "string",
        email: "string",
        languages: {
          additionalProp1: 0,
          additionalProp2: 0,
          additionalProp3: 0,
        },
        activityIndex: 0,
        topLanguage: "string",
        starsCount: 0,
        commitsCount: 0,
        reposCount: 0,
        stackOverflowUrl: "string",
        pullRequestsCount: 0,
        issuesCount: 0,
      },
      {
        username: "Wort",
        commitsTotal: 1113,
        issuesTotal: 13,
        pullRequestTotal: 12,
        mostUsedLanguage: "java",
        description: "string",
        displayName: "string",
        personalWebsite: "string",
        followersCount: 0,
        followingCount: 0,
        location: "string",
        company: "string",
        email: "string",
        languages: {
          additionalProp1: 0,
          additionalProp2: 0,
          additionalProp3: 0,
        },
        activityIndex: 0,
        topLanguage: "string",
        starsCount: 0,
        commitsCount: 0,
        reposCount: 0,
        stackOverflowUrl: "string",
        pullRequestsCount: 0,
        issuesCount: 0,
      },
      {
        username: "Wokkta",
        commitsTotal: 93,
        issuesTotal: 153,
        pullRequestTotal: 122,
        mostUsedLanguage: "js",
        description: "string",
        displayName: "string",
        personalWebsite: "string",
        followersCount: 0,
        followingCount: 0,
        location: "string",
        company: "string",
        email: "string",
        languages: {
          additionalProp1: 0,
          additionalProp2: 0,
          additionalProp3: 0,
        },
        activityIndex: 0,
        topLanguage: "string",
        starsCount: 0,
        commitsCount: 0,
        reposCount: 0,
        stackOverflowUrl: "string",
        pullRequestsCount: 0,
        issuesCount: 0,
      },
      {
        username: "Tolik",
        commitsTotal: 19,
        issuesTotal: 161,
        pullRequestTotal: 143,
        mostUsedLanguage: "python",
        description: "string",
        displayName: "string",
        personalWebsite: "string",
        followersCount: 0,
        followingCount: 0,
        location: "string",
        company: "string",
        email: "string",
        languages: {
          additionalProp1: 0,
          additionalProp2: 0,
          additionalProp3: 0,
        },
        activityIndex: 0,
        topLanguage: "string",
        starsCount: 0,
        commitsCount: 0,
        reposCount: 0,
        stackOverflowUrl: "string",
        pullRequestsCount: 0,
        issuesCount: 0,
      },
      {
        username: "Wort",
        commitsTotal: 1113,
        issuesTotal: 13,
        pullRequestTotal: 12,
        mostUsedLanguage: "java",
        description: "string",
        displayName: "string",
        personalWebsite: "string",
        followersCount: 0,
        followingCount: 0,
        location: "string",
        company: "string",
        email: "string",
        languages: {
          additionalProp1: 0,
          additionalProp2: 0,
          additionalProp3: 0,
        },
        activityIndex: 0,
        topLanguage: "string",
        starsCount: 0,
        commitsCount: 0,
        reposCount: 0,
        stackOverflowUrl: "string",
        pullRequestsCount: 0,
        issuesCount: 0,
      },
      {
        username: "Wokkta",
        commitsTotal: 93,
        issuesTotal: 153,
        pullRequestTotal: 122,
        mostUsedLanguage: "js",
        description: "string",
        displayName: "string",
        personalWebsite: "string",
        followersCount: 0,
        followingCount: 0,
        location: "string",
        company: "string",
        email: "string",
        languages: {
          additionalProp1: 0,
          additionalProp2: 0,
          additionalProp3: 0,
        },
        activityIndex: 0,
        topLanguage: "string",
        starsCount: 0,
        commitsCount: 0,
        reposCount: 0,
        stackOverflowUrl: "string",
        pullRequestsCount: 0,
        issuesCount: 0,
      },
      {
        username: "Tolik",
        commitsTotal: 19,
        issuesTotal: 161,
        pullRequestTotal: 143,
        mostUsedLanguage: "python",
        description: "string",
        displayName: "string",
        personalWebsite: "string",
        followersCount: 0,
        followingCount: 0,
        location: "string",
        company: "string",
        email: "string",
        languages: {
          additionalProp1: 0,
          additionalProp2: 0,
          additionalProp3: 0,
        },
        activityIndex: 0,
        topLanguage: "string",
        starsCount: 0,
        commitsCount: 0,
        reposCount: 0,
        stackOverflowUrl: "string",
        pullRequestsCount: 0,
        issuesCount: 0,
      },
      {
        username: "Wort",
        commitsTotal: 1113,
        issuesTotal: 13,
        pullRequestTotal: 12,
        mostUsedLanguage: "java",
        description: "string",
        displayName: "string",
        personalWebsite: "string",
        followersCount: 0,
        followingCount: 0,
        location: "string",
        company: "string",
        email: "string",
        languages: {
          additionalProp1: 0,
          additionalProp2: 0,
          additionalProp3: 0,
        },
        activityIndex: 0,
        topLanguage: "string",
        starsCount: 0,
        commitsCount: 0,
        reposCount: 0,
        stackOverflowUrl: "string",
        pullRequestsCount: 0,
        issuesCount: 0,
      },
      {
        username: "Wokkta",
        commitsTotal: 93,
        issuesTotal: 153,
        pullRequestTotal: 122,
        mostUsedLanguage: "js",
        description: "string",
        displayName: "string",
        personalWebsite: "string",
        followersCount: 0,
        followingCount: 0,
        location: "string",
        company: "string",
        email: "string",
        languages: {
          additionalProp1: 0,
          additionalProp2: 0,
          additionalProp3: 0,
        },
        activityIndex: 0,
        topLanguage: "string",
        starsCount: 0,
        commitsCount: 0,
        reposCount: 0,
        stackOverflowUrl: "string",
        pullRequestsCount: 0,
        issuesCount: 0,
      },
      {
        username: "Tolik",
        commitsTotal: 19,
        issuesTotal: 161,
        pullRequestTotal: 143,
        mostUsedLanguage: "python",
        description: "string",
        displayName: "string",
        personalWebsite: "string",
        followersCount: 0,
        followingCount: 0,
        location: "string",
        company: "string",
        email: "string",
        languages: {
          additionalProp1: 0,
          additionalProp2: 0,
          additionalProp3: 0,
        },
        activityIndex: 0,
        topLanguage: "string",
        starsCount: 0,
        commitsCount: 0,
        reposCount: 0,
        stackOverflowUrl: "string",
        pullRequestsCount: 0,
        issuesCount: 0,
      },
      {
        username: "Wort",
        commitsTotal: 1113,
        issuesTotal: 13,
        pullRequestTotal: 12,
        mostUsedLanguage: "java",
        description: "string",
        displayName: "string",
        personalWebsite: "string",
        followersCount: 0,
        followingCount: 0,
        location: "string",
        company: "string",
        email: "string",
        languages: {
          additionalProp1: 0,
          additionalProp2: 0,
          additionalProp3: 0,
        },
        activityIndex: 0,
        topLanguage: "string",
        starsCount: 0,
        commitsCount: 0,
        reposCount: 0,
        stackOverflowUrl: "string",
        pullRequestsCount: 0,
        issuesCount: 0,
      },
      {
        username: "Wokkta",
        commitsTotal: 93,
        issuesTotal: 153,
        pullRequestTotal: 122,
        mostUsedLanguage: "js",
        description: "string",
        displayName: "string",
        personalWebsite: "string",
        followersCount: 0,
        followingCount: 0,
        location: "string",
        company: "string",
        email: "string",
        languages: {
          additionalProp1: 0,
          additionalProp2: 0,
          additionalProp3: 0,
        },
        activityIndex: 0,
        topLanguage: "string",
        starsCount: 0,
        commitsCount: 0,
        reposCount: 0,
        stackOverflowUrl: "string",
        pullRequestsCount: 0,
        issuesCount: 0,
      },
      {
        username: "Tolik",
        commitsTotal: 19,
        issuesTotal: 161,
        pullRequestTotal: 143,
        mostUsedLanguage: "python",
        description: "string",
        displayName: "string",
        personalWebsite: "string",
        followersCount: 0,
        followingCount: 0,
        location: "string",
        company: "string",
        email: "string",
        languages: {
          additionalProp1: 0,
          additionalProp2: 0,
          additionalProp3: 0,
        },
        activityIndex: 0,
        topLanguage: "string",
        starsCount: 0,
        commitsCount: 0,
        reposCount: 0,
        stackOverflowUrl: "string",
        pullRequestsCount: 0,
        issuesCount: 0,
      },
      {
        username: "Wort",
        commitsTotal: 1113,
        issuesTotal: 13,
        pullRequestTotal: 12,
        mostUsedLanguage: "java",
        description: "string",
        displayName: "string",
        personalWebsite: "string",
        followersCount: 0,
        followingCount: 0,
        location: "string",
        company: "string",
        email: "string",
        languages: {
          additionalProp1: 0,
          additionalProp2: 0,
          additionalProp3: 0,
        },
        activityIndex: 0,
        topLanguage: "string",
        starsCount: 0,
        commitsCount: 0,
        reposCount: 0,
        stackOverflowUrl: "string",
        pullRequestsCount: 0,
        issuesCount: 0,
      },
      {
        username: "Wokkta",
        commitsTotal: 93,
        issuesTotal: 153,
        pullRequestTotal: 122,
        mostUsedLanguage: "js",
        description: "string",
        displayName: "string",
        personalWebsite: "string",
        followersCount: 0,
        followingCount: 0,
        location: "string",
        company: "string",
        email: "string",
        languages: {
          additionalProp1: 0,
          additionalProp2: 0,
          additionalProp3: 0,
        },
        activityIndex: 0,
        topLanguage: "string",
        starsCount: 0,
        commitsCount: 0,
        reposCount: 0,
        stackOverflowUrl: "string",
        pullRequestsCount: 0,
        issuesCount: 0,
      },
      {
        username: "Tolik",
        commitsTotal: 19,
        issuesTotal: 161,
        pullRequestTotal: 143,
        mostUsedLanguage: "python",
        description: "string",
        displayName: "string",
        personalWebsite: "string",
        followersCount: 0,
        followingCount: 0,
        location: "string",
        company: "string",
        email: "string",
        languages: {
          additionalProp1: 0,
          additionalProp2: 0,
          additionalProp3: 0,
        },
        activityIndex: 0,
        topLanguage: "string",
        starsCount: 0,
        commitsCount: 0,
        reposCount: 0,
        stackOverflowUrl: "string",
        pullRequestsCount: 0,
        issuesCount: 0,
      },
      {
        username: "Wort",
        commitsTotal: 1113,
        issuesTotal: 13,
        pullRequestTotal: 12,
        mostUsedLanguage: "java",
        description: "string",
        displayName: "string",
        personalWebsite: "string",
        followersCount: 0,
        followingCount: 0,
        location: "string",
        company: "string",
        email: "string",
        languages: {
          additionalProp1: 0,
          additionalProp2: 0,
          additionalProp3: 0,
        },
        activityIndex: 0,
        topLanguage: "string",
        starsCount: 0,
        commitsCount: 0,
        reposCount: 0,
        stackOverflowUrl: "string",
        pullRequestsCount: 0,
        issuesCount: 0,
      },
      {
        username: "Wokkta",
        commitsTotal: 93,
        issuesTotal: 153,
        pullRequestTotal: 122,
        mostUsedLanguage: "js",
        description: "string",
        displayName: "string",
        personalWebsite: "string",
        followersCount: 0,
        followingCount: 0,
        location: "string",
        company: "string",
        email: "string",
        languages: {
          additionalProp1: 0,
          additionalProp2: 0,
          additionalProp3: 0,
        },
        activityIndex: 0,
        topLanguage: "string",
        starsCount: 0,
        commitsCount: 0,
        reposCount: 0,
        stackOverflowUrl: "string",
        pullRequestsCount: 0,
        issuesCount: 0,
      },
      {
        username: "Tolik",
        commitsTotal: 19,
        issuesTotal: 161,
        pullRequestTotal: 143,
        mostUsedLanguage: "python",
        description: "string",
        displayName: "string",
        personalWebsite: "string",
        followersCount: 0,
        followingCount: 0,
        location: "string",
        company: "string",
        email: "string",
        languages: {
          additionalProp1: 0,
          additionalProp2: 0,
          additionalProp3: 0,
        },
        activityIndex: 0,
        topLanguage: "string",
        starsCount: 0,
        commitsCount: 0,
        reposCount: 0,
        stackOverflowUrl: "string",
        pullRequestsCount: 0,
        issuesCount: 0,
      },
      {
        username: "Wort",
        commitsTotal: 1113,
        issuesTotal: 13,
        pullRequestTotal: 12,
        mostUsedLanguage: "java",
        description: "string",
        displayName: "string",
        personalWebsite: "string",
        followersCount: 0,
        followingCount: 0,
        location: "string",
        company: "string",
        email: "string",
        languages: {
          additionalProp1: 0,
          additionalProp2: 0,
          additionalProp3: 0,
        },
        activityIndex: 0,
        topLanguage: "string",
        starsCount: 0,
        commitsCount: 0,
        reposCount: 0,
        stackOverflowUrl: "string",
        pullRequestsCount: 0,
        issuesCount: 0,
      },
      {
        username: "Wokkta",
        commitsTotal: 93,
        issuesTotal: 153,
        pullRequestTotal: 122,
        mostUsedLanguage: "js",
        description: "string",
        displayName: "string",
        personalWebsite: "string",
        followersCount: 0,
        followingCount: 0,
        location: "string",
        company: "string",
        email: "string",
        languages: {
          additionalProp1: 0,
          additionalProp2: 0,
          additionalProp3: 0,
        },
        activityIndex: 0,
        topLanguage: "string",
        starsCount: 0,
        commitsCount: 0,
        reposCount: 0,
        stackOverflowUrl: "string",
        pullRequestsCount: 0,
        issuesCount: 0,
      },
      {
        username: "Tolik",
        commitsTotal: 19,
        issuesTotal: 161,
        pullRequestTotal: 143,
        mostUsedLanguage: "python",
        description: "string",
        displayName: "string",
        personalWebsite: "string",
        followersCount: 0,
        followingCount: 0,
        location: "string",
        company: "string",
        email: "string",
        languages: {
          additionalProp1: 0,
          additionalProp2: 0,
          additionalProp3: 0,
        },
        activityIndex: 0,
        topLanguage: "string",
        starsCount: 0,
        commitsCount: 0,
        reposCount: 0,
        stackOverflowUrl: "string",
        pullRequestsCount: 0,
        issuesCount: 0,
      },
      {
        username: "Wort",
        commitsTotal: 1113,
        issuesTotal: 13,
        pullRequestTotal: 12,
        mostUsedLanguage: "java",
        description: "string",
        displayName: "string",
        personalWebsite: "string",
        followersCount: 0,
        followingCount: 0,
        location: "string",
        company: "string",
        email: "string",
        languages: {
          additionalProp1: 0,
          additionalProp2: 0,
          additionalProp3: 0,
        },
        activityIndex: 0,
        topLanguage: "string",
        starsCount: 0,
        commitsCount: 0,
        reposCount: 0,
        stackOverflowUrl: "string",
        pullRequestsCount: 0,
        issuesCount: 0,
      },
      {
        username: "Wokkta",
        commitsTotal: 93,
        issuesTotal: 153,
        pullRequestTotal: 122,
        mostUsedLanguage: "js",
        description: "string",
        displayName: "string",
        personalWebsite: "string",
        followersCount: 0,
        followingCount: 0,
        location: "string",
        company: "string",
        email: "string",
        languages: {
          additionalProp1: 0,
          additionalProp2: 0,
          additionalProp3: 0,
        },
        activityIndex: 0,
        topLanguage: "string",
        starsCount: 0,
        commitsCount: 0,
        reposCount: 0,
        stackOverflowUrl: "string",
        pullRequestsCount: 0,
        issuesCount: 0,
      },
      {
        username: "Tolik",
        commitsTotal: 19,
        issuesTotal: 161,
        pullRequestTotal: 143,
        mostUsedLanguage: "python",
        description: "string",
        displayName: "string",
        personalWebsite: "string",
        followersCount: 0,
        followingCount: 0,
        location: "string",
        company: "string",
        email: "string",
        languages: {
          additionalProp1: 0,
          additionalProp2: 0,
          additionalProp3: 0,
        },
        activityIndex: 0,
        topLanguage: "string",
        starsCount: 0,
        commitsCount: 0,
        reposCount: 0,
        stackOverflowUrl: "string",
        pullRequestsCount: 0,
        issuesCount: 0,
      },
      {
        username: "Wort",
        commitsTotal: 1113,
        issuesTotal: 13,
        pullRequestTotal: 12,
        mostUsedLanguage: "java",
        description: "string",
        displayName: "string",
        personalWebsite: "string",
        followersCount: 0,
        followingCount: 0,
        location: "string",
        company: "string",
        email: "string",
        languages: {
          additionalProp1: 0,
          additionalProp2: 0,
          additionalProp3: 0,
        },
        activityIndex: 0,
        topLanguage: "string",
        starsCount: 0,
        commitsCount: 0,
        reposCount: 0,
        stackOverflowUrl: "string",
        pullRequestsCount: 0,
        issuesCount: 0,
      },
    ],
  },
  reducers: {
    setMvpList(state, action) {
      state.mvpList = action.payload;
    },
  },
});

// Action creators are generated for each case reducer function
export const { setMvpList } = mvpListSlice.actions;

export default mvpListSlice.reducer;
